"""Add blocked unblocked webhook events

Revision ID: fe4b29427755
Revises: bab119682559
Create Date: 2025-12-05 16:17:54.504623+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4b29427755'
down_revision: Union[str, None] = 'bab119682559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stalker_webhook_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_device_blocked', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('event_device_unblocked', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stalker_webhook_config', schema=None) as batch_op:
        batch_op.drop_column('event_device_unblocked')
        batch_op.drop_column('event_device_blocked')

    # ### end Alembic commands ###
